apiVersion: v1
kind: Service
metadata:
  name: t3-client-service
  labels:
    {{- include "t3-client.labels" . | nindent 4 }}
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      nodePort: 32000
  selector:
    app: flask
